<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>8</WarningLevel>
    <NoWarn>1701;1702;IDE0161;IDE0053;CA1861;S4487;CA1823;S1144</NoWarn>
    <WarningsNotAsErrors></WarningsNotAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>8</WarningLevel>
    <NoWarn>1701;1702;IDE0161;IDE0053;CA1861;S4487;CA1823;S1144</NoWarn>
    <WarningsNotAsErrors></WarningsNotAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="Hangfire.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="ArchitectureTests" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration" />
    <Folder Include="Caching" />
    <Folder Include="Database\Migrations\" />
    <Folder Include="Storage" />
    <Folder Include="Utils\" />
  </ItemGroup>


</Project>
