// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250930145848_Update2")]
    partial class Update2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Attendance.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid?>("AttendanceScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_schedule_id");

                    b.Property<int?>("BreakMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("break_minutes");

                    b.Property<string>("CheckInMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("check_in_method");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<string>("CheckOutMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("check_out_method");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<int?>("EarlyLeaveMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("early_leave_minutes");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<int?>("LateMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("late_minutes");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int?>("OvertimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("overtime_minutes");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int?>("WorkingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("working_minutes");

                    b.HasKey("Id")
                        .HasName("pk_attendances");

                    b.HasIndex("AttendanceScheduleId")
                        .HasDatabaseName("ix_attendances_attendance_schedule_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_attendances_date");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_attendances_shift_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_attendances_status");

                    b.HasIndex("EmployeeId", "Date")
                        .HasDatabaseName("ix_attendances_employee_id_date");

                    b.ToTable("Attendances", "public");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.AttendanceBreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttendanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_id");

                    b.Property<string>("BreakType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("break_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_attendance_breaks");

                    b.HasIndex("AttendanceId")
                        .HasDatabaseName("ix_attendance_breaks_attendance_id");

                    b.HasIndex("BreakType")
                        .HasDatabaseName("ix_attendance_breaks_break_type");

                    b.HasIndex("EndTime")
                        .HasDatabaseName("ix_attendance_breaks_end_time");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_attendance_breaks_start_time");

                    b.ToTable("AttendanceBreaks", "public");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.AttendanceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttendanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_id");

                    b.Property<string>("AttendanceStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("attendance_status");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("card_no");

                    b.Property<int?>("CardReaderNo")
                        .HasColumnType("integer")
                        .HasColumnName("card_reader_no");

                    b.Property<int?>("CardType")
                        .HasColumnType("integer")
                        .HasColumnName("card_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrentVerifyMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_verify_mode");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<int?>("DoorNo")
                        .HasColumnType("integer")
                        .HasColumnName("door_no");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeNoString")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_no_string");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<int?>("Major")
                        .HasColumnType("integer")
                        .HasColumnName("major");

                    b.Property<string>("Mask")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mask");

                    b.Property<int?>("Minor")
                        .HasColumnType("integer")
                        .HasColumnName("minor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PictureURL")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("picture_url");

                    b.Property<int?>("SerialNo")
                        .HasColumnType("integer")
                        .HasColumnName("serial_no");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<string>("UserType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_type");

                    b.Property<Guid?>("WorkLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_location_id");

                    b.HasKey("Id")
                        .HasName("pk_attendance_logs");

                    b.HasIndex("AttendanceId")
                        .HasDatabaseName("ix_attendance_logs_attendance_id");

                    b.HasIndex("AttendanceStatus")
                        .HasDatabaseName("ix_attendance_logs_attendance_status");

                    b.HasIndex("CardNo")
                        .HasDatabaseName("ix_attendance_logs_card_no");

                    b.HasIndex("CardReaderNo")
                        .HasDatabaseName("ix_attendance_logs_card_reader_no");

                    b.HasIndex("DoorNo")
                        .HasDatabaseName("ix_attendance_logs_door_no");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_attendance_logs_employee_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_attendance_logs_organization_id");

                    b.HasIndex("SerialNo")
                        .HasDatabaseName("ix_attendance_logs_serial_no");

                    b.HasIndex("Time")
                        .HasDatabaseName("ix_attendance_logs_time");

                    b.HasIndex("WorkLocationId")
                        .HasDatabaseName("ix_attendance_logs_work_location_id");

                    b.ToTable("AttendanceLogs", "public");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.AttendanceSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ExcludedDates")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("excluded_dates");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schedule_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_attendance_schedules");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("ix_attendance_schedules_end_date");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_attendance_schedules_is_active");

                    b.HasIndex("ScheduleType")
                        .HasDatabaseName("ix_attendance_schedules_schedule_type");

                    b.HasIndex("EmployeeId", "StartDate")
                        .HasDatabaseName("ix_attendance_schedules_employee_id_start_date");

                    b.ToTable("AttendanceSchedules", "public");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.Leave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("leave_type");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_leaves");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_leaves_employee_id");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("ix_leaves_end_date");

                    b.HasIndex("LeaveType")
                        .HasDatabaseName("ix_leaves_leave_type");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_leaves_start_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_leaves_status");

                    b.ToTable("Leaves", "public");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.ScheduleDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttendanceScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_schedule_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("day_of_week");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.HasKey("Id")
                        .HasName("pk_schedule_days");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_schedule_days_is_active");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_schedule_days_shift_id");

                    b.HasIndex("AttendanceScheduleId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_days_attendance_schedule_id_day_of_week");

                    b.ToTable("ScheduleDays", "public");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.ScheduleIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttendanceScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_schedule_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exception_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.HasKey("Id")
                        .HasName("pk_schedule_issues");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_schedule_issues_date");

                    b.HasIndex("ExceptionType")
                        .HasDatabaseName("ix_schedule_issues_exception_type");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_schedule_issues_shift_id");

                    b.HasIndex("AttendanceScheduleId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_issues_attendance_schedule_id_date");

                    b.ToTable("ScheduleIssues", "public");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.SecurityAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalData")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("additional_data");

                    b.Property<double?>("BiometricConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("biometric_confidence");

                    b.Property<Guid?>("BiometricId")
                        .HasColumnType("uuid")
                        .HasColumnName("biometric_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean")
                        .HasColumnName("is_successful");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<double?>("LocationLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("location_latitude");

                    b.Property<double?>("LocationLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("location_longitude");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_security_audit_logs");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_security_audit_logs_device_id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_security_audit_logs_employee_id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_security_audit_logs_event_type");

                    b.HasIndex("IsSuccessful")
                        .HasDatabaseName("ix_security_audit_logs_is_successful");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_security_audit_logs_severity");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_security_audit_logs_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_security_audit_logs_user_id");

                    b.ToTable("SecurityAuditLogs", "public");
                });

            modelBuilder.Entity("Domain.Entities.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("text")
                        .HasColumnName("device_model");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<string>("Features")
                        .HasColumnType("text")
                        .HasColumnName("features");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("text")
                        .HasColumnName("firmware_version");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("IsupKey")
                        .HasColumnType("text")
                        .HasColumnName("isup_key");

                    b.Property<DateTime?>("LastConnected")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connected");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text")
                        .HasColumnName("mac_address");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Port")
                        .HasColumnType("text")
                        .HasColumnName("port");

                    b.Property<string>("Protocol")
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_device_id");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("ix_devices_ip_address");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_devices_organization_id");

                    b.ToTable("Devices", "public");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("blob_path");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_attachments_employee_id");

                    b.ToTable("Attachments", "public");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<Guid>("Id"), 1L, null, null, null, null, null);

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_id");

                    b.Property<string>("FaceImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("face_image_url");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("family_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("FourthName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fourth_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsManager")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manager");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("NationalIdBackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("national_id_back_url");

                    b.Property<string>("NationalIdFrontUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("national_id_front_url");

                    b.Property<Guid?>("OrganizationalUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizational_unit_id");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_image_url");

                    b.Property<string>("RFID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rfid");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("second_name");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("third_name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_email");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_employee_id");

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_employees_full_name");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_employees_manager_id");

                    b.HasIndex("OrganizationalUnitId")
                        .HasDatabaseName("ix_employees_organizational_unit_id");

                    b.HasIndex("RFID")
                        .HasDatabaseName("ix_employees_rfid");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("ix_employees_shift_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_user_id");

                    b.ToTable("Employees", "public");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_holidays");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_holidays_date");

                    b.HasIndex("IsRecurring")
                        .HasDatabaseName("ix_holidays_is_recurring");

                    b.HasIndex("OrganizationId", "Date", "IsRecurring")
                        .IsUnique()
                        .HasDatabaseName("ix_holidays_organization_id_date_is_recurring");

                    b.ToTable("Holidays", "public");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.OrganizationalUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<Guid?>("ParentUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_unit_id");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_code");

                    b.Property<string>("UnitDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("unit_description");

                    b.Property<int?>("UnitLevel")
                        .HasColumnType("integer")
                        .HasColumnName("unit_level");

                    b.Property<string>("UnitLogo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("unit_logo");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unit_name");

                    b.HasKey("Id")
                        .HasName("pk_organizational_units");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_organizational_units_manager_id");

                    b.HasIndex("ParentUnitId")
                        .HasDatabaseName("ix_organizational_units_parent_unit_id");

                    b.HasIndex("UnitCode")
                        .IsUnique()
                        .HasDatabaseName("ix_organizational_units_unit_code");

                    b.HasIndex("UnitName")
                        .HasDatabaseName("ix_organizational_units_unit_name");

                    b.ToTable("OrganizationalUnits", "public");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowEarlyCheckIn")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_early_check_in");

                    b.Property<bool>("AllowLateCheckOut")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_late_check_out");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int?>("GracePeriodMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("grace_period_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<int?>("MaxLateMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("max_late_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shift_type");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_shifts");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_shifts_is_active");

                    b.HasIndex("ShiftType")
                        .HasDatabaseName("ix_shifts_shift_type");

                    b.ToTable("Shifts", "public");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.WorkLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("BeaconId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("beacon_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("integer")
                        .HasColumnName("radius_meters");

                    b.Property<string>("WifiSSID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wifi_ssid");

                    b.HasKey("Id")
                        .HasName("pk_work_locations");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_work_locations_is_active");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("ix_work_locations_latitude_longitude");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_work_locations_organization_id_name");

                    b.ToTable("WorkLocations", "public");
                });

            modelBuilder.Entity("Domain.Entities.Users.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("resource");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.ToTable("permission", "public");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_date");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<Guid?>("OrganizationalUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizational_unit_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_login");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("OrganizationalUnitId")
                        .HasDatabaseName("ix_users_organizational_unit_id");

                    b.HasIndex("UserLogin")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_login");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("Domain.Entities.Users.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DoneProcdureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("done_procdure_date");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_updated_by");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_permission");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_user_permission_permission_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_permission_user_id");

                    b.ToTable("user_permission", "public");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.PrimitiveCollection<List<string>>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_items");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_todo_items_user_id");

                    b.ToTable("todo_items", "public");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.Attendance", b =>
                {
                    b.HasOne("Domain.Entities.Attendance.AttendanceSchedule", "AttendanceSchedule")
                        .WithMany("Attendances")
                        .HasForeignKey("AttendanceScheduleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_attendances_attendance_schedules_attendance_schedule_id");

                    b.HasOne("Domain.Entities.Organizations.Employee", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendances_employees_employee_id");

                    b.HasOne("Domain.Entities.Organizations.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_attendances_shifts_shift_id");

                    b.Navigation("AttendanceSchedule");

                    b.Navigation("Employee");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.AttendanceBreak", b =>
                {
                    b.HasOne("Domain.Entities.Attendance.Attendance", "Attendance")
                        .WithMany("Breaks")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_breaks_attendances_attendance_id");

                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.AttendanceLog", b =>
                {
                    b.HasOne("Domain.Entities.Attendance.Attendance", "Attendance")
                        .WithMany("Logs")
                        .HasForeignKey("AttendanceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_attendance_logs_attendances_attendance_id");

                    b.HasOne("Domain.Entities.Organizations.Employee", "Employee")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_logs_employees_employee_id");

                    b.HasOne("Domain.Entities.Organizations.OrganizationalUnit", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attendance_logs_organizational_units_organization_id");

                    b.HasOne("Domain.Entities.Organizations.WorkLocation", "WorkLocation")
                        .WithMany()
                        .HasForeignKey("WorkLocationId")
                        .HasConstraintName("fk_attendance_logs_work_locations_work_location_id");

                    b.Navigation("Attendance");

                    b.Navigation("Employee");

                    b.Navigation("Organization");

                    b.Navigation("WorkLocation");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.AttendanceSchedule", b =>
                {
                    b.HasOne("Domain.Entities.Organizations.Employee", "Employee")
                        .WithMany("AttendanceSchedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_schedules_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.Leave", b =>
                {
                    b.HasOne("Domain.Entities.Organizations.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leaves_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.ScheduleDay", b =>
                {
                    b.HasOne("Domain.Entities.Attendance.AttendanceSchedule", "AttendanceSchedule")
                        .WithMany("ScheduleDays")
                        .HasForeignKey("AttendanceScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_days_attendance_schedules_attendance_schedule_id");

                    b.HasOne("Domain.Entities.Organizations.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_days_shifts_shift_id");

                    b.Navigation("AttendanceSchedule");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.ScheduleIssue", b =>
                {
                    b.HasOne("Domain.Entities.Attendance.AttendanceSchedule", "AttendanceSchedule")
                        .WithMany("Exceptions")
                        .HasForeignKey("AttendanceScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_issues_attendance_schedules_attendance_schedule_id");

                    b.HasOne("Domain.Entities.Organizations.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_issues_shifts_shift_id");

                    b.Navigation("AttendanceSchedule");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.SecurityAuditLog", b =>
                {
                    b.HasOne("Domain.Entities.Organizations.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_security_audit_logs_employees_employee_id");

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_security_audit_logs_users_user_id");

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Devices.Device", b =>
                {
                    b.HasOne("Domain.Entities.Organizations.OrganizationalUnit", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_devices_organizational_units_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.Attachment", b =>
                {
                    b.HasOne("Domain.Entities.Organizations.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_employees_employee_id");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.Employee", b =>
                {
                    b.HasOne("Domain.Entities.Organizations.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_employees_employees_manager_id");

                    b.HasOne("Domain.Entities.Organizations.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany("Employees")
                        .HasForeignKey("OrganizationalUnitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_employees_organizational_units_organizational_unit_id");

                    b.HasOne("Domain.Entities.Organizations.Shift", null)
                        .WithMany("Employees")
                        .HasForeignKey("ShiftId")
                        .HasConstraintName("fk_employees_shifts_shift_id");

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Organizations.Employee", "UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_employees_users_user_id");

                    b.Navigation("Manager");

                    b.Navigation("OrganizationalUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.Holiday", b =>
                {
                    b.HasOne("Domain.Entities.Organizations.OrganizationalUnit", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_holidays_organizational_units_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.OrganizationalUnit", b =>
                {
                    b.HasOne("Domain.Entities.Organizations.Employee", "Manager")
                        .WithMany("ManagedUnits")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_organizational_units_employees_manager_id");

                    b.HasOne("Domain.Entities.Organizations.OrganizationalUnit", "ParentUnit")
                        .WithMany("ChildUnits")
                        .HasForeignKey("ParentUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organizational_units_organizational_units_parent_unit_id");

                    b.Navigation("Manager");

                    b.Navigation("ParentUnit");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.WorkLocation", b =>
                {
                    b.HasOne("Domain.Entities.Organizations.OrganizationalUnit", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_locations_organizational_units_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.HasOne("Domain.Entities.Organizations.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationalUnitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_organizational_units_organizational_unit_id");

                    b.Navigation("OrganizationalUnit");
                });

            modelBuilder.Entity("Domain.Entities.Users.UserPermission", b =>
                {
                    b.HasOne("Domain.Entities.Users.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permission_permission_permission_id");

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permission_users_user_id");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_items_users_user_id");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.Attendance", b =>
                {
                    b.Navigation("Breaks");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Domain.Entities.Attendance.AttendanceSchedule", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Exceptions");

                    b.Navigation("ScheduleDays");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.Employee", b =>
                {
                    b.Navigation("AttendanceLogs");

                    b.Navigation("AttendanceSchedules");

                    b.Navigation("Attendances");

                    b.Navigation("ManagedUnits");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.OrganizationalUnit", b =>
                {
                    b.Navigation("ChildUnits");

                    b.Navigation("Employees");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Organizations.Shift", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.Entities.Users.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
